name: blackjack
description: Flutter Blackjack

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_style: "^1.2.0"
  test: "^1.6.1"




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/blackjack-1.jpg
    - images/cards/2c.gif
    - images/cards/2d.gif
    - images/cards/2h.gif
    - images/cards/2s.gif
    - images/cards/3c.gif
    - images/cards/3d.gif
    - images/cards/3h.gif
    - images/cards/3s.gif
    - images/cards/4c.gif
    - images/cards/4d.gif
    - images/cards/4h.gif
    - images/cards/4s.gif
    - images/cards/5c.gif
    - images/cards/5d.gif
    - images/cards/5h.gif
    - images/cards/5s.gif
    - images/cards/6c.gif
    - images/cards/6d.gif
    - images/cards/6h.gif
    - images/cards/6s.gif
    - images/cards/7c.gif
    - images/cards/7d.gif
    - images/cards/7h.gif
    - images/cards/7s.gif
    - images/cards/8c.gif
    - images/cards/8d.gif
    - images/cards/8h.gif
    - images/cards/8s.gif
    - images/cards/9c.gif
    - images/cards/9d.gif
    - images/cards/9h.gif
    - images/cards/9s.gif
    - images/cards/ac.gif
    - images/cards/ad.gif
    - images/cards/ah.gif
    - images/cards/as.gif
    - images/cards/jc.gif
    - images/cards/jd.gif
    - images/cards/jh.gif
    - images/cards/js.gif
    - images/cards/kc.gif
    - images/cards/kd.gif
    - images/cards/kh.gif
    - images/cards/ks.gif
    - images/cards/qc.gif
    - images/cards/qd.gif
    - images/cards/qh.gif
    - images/cards/qs.gif
    - images/cards/tc.gif
    - images/cards/td.gif
    - images/cards/th.gif
    - images/cards/ts.gif

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
